# Generated by Django 4.2.9 on 2024-07-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(default='fd38133d34f0403a9f488c6f300806bf', editable=False, max_length=32),
        ),
    ]
