# Generated by Django 4.2.9 on 2024-07-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(default='f17674cc49b847efba79bf16d2ace18f', editable=False, max_length=32),
        ),
    ]
