# Generated by Django 4.2.9 on 2024-07-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_email_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(default='57ea523041ed4090835f2a1e1d3392da', editable=False, max_length=32),
        ),
    ]
