# Generated by Django 4.2.9 on 2024-07-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_email_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(default='4863c8d062d746149e520a501309ee30', editable=False, max_length=32),
        ),
    ]
