# Generated by Django 4.2.9 on 2024-07-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_email_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(default='92092c287a344557b41457f3fc43714b', editable=False, max_length=32),
        ),
    ]
