# Generated by Django 4.2.9 on 2024-07-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_email_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(default='172a09d963604c369b1388190a44309b', editable=False, max_length=32),
        ),
    ]
