# Generated by Django 4.2.9 on 2024-08-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_email_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(default='23fb833e754944ab917ae961282f910c', editable=False, max_length=32),
        ),
    ]
