# Generated by Django 4.2.9 on 2024-08-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_email_verification_code_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(default='88a36f1134ec489e890d98924aedc34b', editable=False, max_length=32),
        ),
    ]
