# Generated by Django 4.2.9 on 2024-08-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_email_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firebase_uid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='free_credits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='recharge_credits',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_level',
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(default='735a3bce33814e63a3542b23fbf4506a', editable=False, max_length=32),
        ),
    ]
