# Generated by Django 4.2.9 on 2024-08-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_user_firebase_uid_remove_user_free_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(default='048ac3bd603c49d9960beb214ed81dc6', editable=False, max_length=32),
        ),
    ]
