# Generated by Django 4.2.9 on 2024-08-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_email_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(default='af4655b3ce164b80ba466bd8afb499ba', editable=False, max_length=32),
        ),
    ]
