# Generated by Django 4.2.9 on 2024-08-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_email_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(default='a42ac451773a4d31bd8d8065a0c80839', editable=False, max_length=32),
        ),
    ]
