# Generated by Django 4.2.9 on 2024-08-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_email_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(default='0a6ae9c2b0b047adafa72000b2a88674', editable=False, max_length=32),
        ),
    ]
