# Generated by Django 4.2.9 on 2024-08-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_email_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
