# Generated by Django 4.2.9 on 2024-09-22 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_problem_problem_type'),
        ('payments', '0005_remove_payment_problem_payment_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='store.problem'),
        ),
    ]
