# Generated by Django 4.2.9 on 2024-08-01 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_alter_problem_detailed_section_alter_problem_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('question_type', models.CharField(choices=[('complaint', 'Complaint'), ('suggestion', 'Suggestion')], max_length=255)),
                ('processing_result', models.CharField(choices=[('progress', 'Progress'), ('resolved', 'Resolved')], default='progress', max_length=255)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
