# Generated by Django 4.2.9 on 2024-08-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_processing_result_report_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='processing_status',
            field=models.CharField(choices=[('Proccessing', 'Proccessing'), ('Resolved', 'Resolved')], default='Proccessing', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='question_type',
            field=models.CharField(choices=[('Incorrect Answer', 'Incorrect Answer'), ('Defective', 'Defective'), ('Suggestion', 'Suggestion')], max_length=255),
        ),
    ]
