# Generated by Django 4.2.9 on 2024-08-14 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('reports', '0003_alter_report_processing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='payment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='payments.payment'),
            preserve_default=False,
        ),
    ]
