# Generated by Django 4.2.9 on 2024-08-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='problem',
        ),
        migrations.AlterField(
            model_name='report',
            name='processing_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Resolved', 'Resolved')], default='Processing', max_length=255),
        ),
    ]
