# Generated by Django 4.2.9 on 2024-07-31 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('Kindergarten', 'Kindergarten'), ('USA grade 1', 'USA grade 1'), ('USA grade 2', 'USA grade 2'), ('USA grade 3', 'USA grade 3'), ('USA grade 4', 'USA grade 4'), ('USA grade 5', 'USA grade 5'), ('USA grade 6', 'USA grade 6'), ('USA grade 7', 'USA grade 7'), ('USA grade 8', 'USA grade 8'), ('Algebra 1', 'Algebra 1'), ('Geometry', 'Geometry'), ('Algebra 2', 'Algebra 2'), ('Trigonometry', 'Trigonometry'), ('Precalculus', 'Precalculus'), ('High school statistics', 'High school statistics'), ('Statistics and probability', 'Statistics and probability'), ('Linear algebra', 'Linear algebra'), ('Differential equations', 'Differential equations'), ('Multivariable calculus', 'Multivariable calculus'), ('AP Calculus BC', 'AP Calculus BC'), ('AP Calculus AB', 'AP Calculus AB'), ('AP Statistics', 'AP Statistics')], max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('detailed_section', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('difficulty', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pages', models.IntegerField()),
                ('problems', models.IntegerField()),
                ('preview_image', models.ImageField(blank=True, default='', null=True, upload_to=store.models.get_image_upload_path)),
                ('file', models.FileField(upload_to=store.models.get_file_upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
