# Generated by Django 4.2.9 on 2024-08-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_problem_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
