# Generated by Django 4.2.9 on 2024-08-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_problem_type_alter_problem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('Liberal Arts', 'Liberal Arts'), ('English', 'English'), ('STEM', 'STEM'), ('SAT', 'SAT')], help_text='* required', max_length=25),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Short Answer', 'Short Answer'), ('Mathematical Modeling', 'Mathematical Modeling'), ('Learning Through Discussion', 'Learning Through Discussion'), ('STEAM', 'STEAM'), ('Math Puzzle', 'Math Puzzle'), ('Math for Literacy', 'Math for Literacy'), ('Physice', 'Physice'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('E.S.S', 'E.S.S'), ('Sentence Completion', 'Sentence Completion'), ('Text Completion', 'Text Completion'), ('Reading Comprehension', 'Reading Comprehension'), ('Homeschooling', 'Homeschooling'), ('School Classes', 'School Classes')], default='Short Answer', help_text='* required', max_length=30),
        ),
    ]
