# Generated by Django 4.2.9 on 2024-08-01 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_problem_subject_alter_problem_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='category',
            new_name='unit',
        ),
    ]
