# Generated by Django 4.2.9 on 2024-08-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_problem_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(help_text='* 100글자 이내로 작성해 주세요.'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')], default=1, help_text='* 상 중 하 등급으로 구분됩니다.'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(help_text='* 30글자 이내 작성해 주세요.', max_length=200),
        ),
    ]
