# Generated by Django 4.2.9 on 2024-09-20 06:05

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_problem_detailed_section_alter_problem_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='is_free',
            field=models.BooleanField(default=False, help_text='공짜일 경우에는 선택해 주세요.'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(help_text='* 300글자 이내로 작성해 주세요.'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='detailed_section',
            field=models.CharField(blank=True, default='', help_text='선택 사항(수학 필수)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='file',
            field=models.FileField(blank=True, default='', help_text='* required', null=True, upload_to=store.models.get_file_upload_path),
        ),
        migrations.AlterField(
            model_name='problem',
            name='grade',
            field=models.CharField(blank=True, choices=[('Kindergarten', 'Kindergarten'), ('USA grade 1', 'USA grade 1'), ('USA grade 2', 'USA grade 2'), ('USA grade 3', 'USA grade 3'), ('USA grade 4', 'USA grade 4'), ('USA grade 5', 'USA grade 5'), ('USA grade 6', 'USA grade 6'), ('USA grade 7', 'USA grade 7'), ('USA grade 8', 'USA grade 8'), ('Algebra 1', 'Algebra 1'), ('Geometry', 'Geometry'), ('Algebra 2', 'Algebra 2'), ('Trigonometry', 'Trigonometry'), ('Precalculus', 'Precalculus'), ('High school statistics', 'High school statistics'), ('Statistics and probability', 'Statistics and probability'), ('Linear algebra', 'Linear algebra'), ('Differential equations', 'Differential equations'), ('Multivariable calculus', 'Multivariable calculus'), ('AP Calculus BC', 'AP Calculus BC'), ('AP Calculus AB', 'AP Calculus AB'), ('AP Statistics', 'AP Statistics')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='preview_image',
            field=models.ImageField(blank=True, default='', help_text='600 X 800 jpg, png , SVG 이미지만 올릴 수 있습니다.', null=True, upload_to=store.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='problem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='*달러 기준이며, $5 ~ $10,000 사이에서 입력해야 합니다.', max_digits=7),
        ),
        migrations.AlterField(
            model_name='problem',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('Liberal Arts', 'Liberal Arts'), ('English', 'English'), ('STEM', 'STEM'), ('SAT', 'SAT')], help_text='* required', max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(help_text='* 100글자 이내 작성해 주세요.', max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Short Answer', 'Short Answer'), ('Mathematical Modeling', 'Mathematical Modeling'), ('Learning Through Discussion', 'Learning Through Discussion'), ('STEAM', 'STEAM'), ('Math Puzzle', 'Math Puzzle'), ('Math for Literacy', 'Math for Literacy'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('E.S.S', 'E.S.S'), ('Sentence Completion', 'Sentence Completion'), ('Text Completion', 'Text Completion'), ('Reading Comprehension', 'Reading Comprehension'), ('Homeschooling', 'Homeschooling'), ('School Classes', 'School Classes'), ('Math', 'Math'), ('English', 'English')], default='Short Answer', help_text='* required', max_length=50),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='unit',
        ),
        migrations.AddField(
            model_name='problem',
            name='unit',
            field=models.ManyToManyField(related_name='Unit', to='store.unittype'),
        ),
    ]
