# Generated by Django 4.2.9 on 2024-09-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_sectiontype_unittype_problem_is_free_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='detailed_section',
        ),
        migrations.AddField(
            model_name='problem',
            name='detailed_section',
            field=models.ManyToManyField(related_name='DetailSection', to='store.sectiontype'),
        ),
    ]
