# Generated by Django 4.2.9 on 2024-09-21 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0012_remove_problem_detailed_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(blank=True, choices=[('Nomal', 'nomal'), ('Premium', 'premium'), ('Best', 'best')], default='Nomal', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='store.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'problem')},
            },
        ),
    ]
