# Generated by Django 4.2.9 on 2024-09-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_problem_problem_type_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(blank=True, choices=[('Normal', 'normal'), ('Premium', 'premium'), ('Best', 'best')], default='Normal', max_length=20, null=True),
        ),
    ]
