# Generated by Django 4.2.9 on 2024-09-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_problem_problem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='*달러 기준이며, $5 ~ $10,000 사이에서 입력해야 합니다.', max_digits=7, null=True),
        ),
    ]
