# Generated by Django 4.2.9 on 2024-09-26 21:49

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_problem_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='preview_image',
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Premium', 'Premium'), ('Best', 'Best')], default='Normal', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PreviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='600 X 800 jpg, png, SVG 이미지만 업로드 가능합니다.', null=True, upload_to=store.models.get_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_images', to='store.problem')),
            ],
        ),
    ]
