# Generated by Django 4.2.9 on 2024-09-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_problem_preview_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='이미지 URL을 입력하세요.', null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(db_index=True, help_text='* 300글자 이내로 작성해 주세요.'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(db_index=True, help_text='* 100글자 이내 작성해 주세요.', max_length=100),
        ),
    ]
