# Generated by Django 4.2.9 on 2024-10-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_problem_is_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='*달러 기준이며, $1 ~ $100 사이에서 입력해야 합니다.', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='*달러 기준이며, $1 ~ $100 사이에서 입력해야 합니다.', max_digits=7),
        ),
    ]
