# Generated by Django 4.2.9 on 2024-10-08 10:43

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_problem_discounted_price_alter_problem_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-created_date'], 'verbose_name': 'Problem', 'verbose_name_plural': 'Problems'},
        ),
        migrations.AlterField(
            model_name='problem',
            name='file',
            field=models.FileField(default='', help_text='* required', upload_to=store.models.get_file_upload_path),
        ),
        migrations.AlterField(
            model_name='problem',
            name='pages',
            field=models.PositiveSmallIntegerField(help_text='* PDF (Pages number)'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problems',
            field=models.PositiveSmallIntegerField(help_text='* PDF (Problem Numbers)'),
        ),
    ]
