# Generated by Django 4.2.9 on 2024-10-09 12:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_problem_options_alter_problem_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Multiple Choice', 'Multiple Choice'), ('Short Answer', 'Short Answer'), ('Mathematical Modeling', 'Mathematical Modeling'), ('Learning Through Discussion', 'Learning Through Discussion'), ('STEAM', 'STEAM'), ('Math Puzzle', 'Math Puzzle'), ('Math for Literacy', 'Math for Literacy'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('E.S.S', 'E.S.S'), ('Sentence Completion', 'Sentence Completion'), ('Text Completion', 'Text Completion'), ('Reading Comprehension', 'Reading Comprehension'), ('Homeschooling', 'Homeschooling'), ('School Classes', 'School Classes'), ('Math', 'Math'), ('English', 'English')], default='Short Answer', help_text='* select one or more types', max_length=246),
        ),
    ]
