# Generated by Django 4.2.9 on 2024-10-10 06:15

from django.db import migrations, models
import store.models
import store.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_problem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='file',
            field=models.FileField(blank=True, default='', help_text='* required', null=True, storage=store.storage_backends.AttachmentS3Boto3Storage(), upload_to=store.models.get_file_upload_path),
        ),
    ]
