# Generated by Django 4.2.9 on 2024-10-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_problem_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiontype',
            name='subject',
            field=models.CharField(blank=True, choices=[('Math', 'Math'), ('Science', 'Science'), ('Liberal Arts', 'Liberal Arts'), ('English', 'English'), ('STEM', 'STEM'), ('SAT', 'SAT')], help_text='* required', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unittype',
            name='subject',
            field=models.CharField(blank=True, choices=[('Math', 'Math'), ('Science', 'Science'), ('Liberal Arts', 'Liberal Arts'), ('English', 'English'), ('STEM', 'STEM'), ('SAT', 'SAT')], help_text='* required', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='previewimage',
            name='image_url',
            field=models.CharField(blank=True, help_text='이미지 URL을 입력하세요.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='detailed_section',
            field=models.ManyToManyField(blank=True, related_name='DetailSection', to='store.sectiontype'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='is_view',
            field=models.BooleanField(db_index=True, default=True, help_text='비공개일때는 체크를 제거해 주세요.'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('Liberal Arts', 'Liberal Arts'), ('English', 'English'), ('STEM', 'STEM'), ('SAT', 'SAT')], db_index=True, help_text='* required', max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='unit',
            field=models.ManyToManyField(blank=True, related_name='problems', to='store.unittype'),
        ),
        migrations.AlterField(
            model_name='sectiontype',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
