# Generated by Django 5.1.6 on 2025-03-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_sectiontype_subject_unittype_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewimage',
            name='image',
            field=models.ImageField(blank=True, help_text='600 X 800 jpg, png, SVG 이미지만 업로드 가능합니다.', null=True, upload_to='images/'),
        ),
    ]
